AllCops:
  Exclude:
    - "db/**/*"
    - "config/**/*"
    - "tmp/**/*"
    - "ssl_certificates/**/*"
    - "bin/**/*"
  TargetRubyVersion: 2.6

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - spec/*
    - spec/**
    - spec/**/**

Metrics/LineLength:
  Exclude:
    - spec/*
    - spec/**
    - spec/**/**
  Max: 100

Airbnb/RspecDescribeOrContextUnderNamespace:
  Enabled: false

Airbnb/ContinuationSlash:
  Enabled: false

Airbnb/RspecEnvironmentModification:
  Enabled: false
